### ISSUE TITLE
Will there be update package? 

### ISSUE THREAD

**Issue by Dreamail** [Neskol/Maichart-Converts#2]
Sometimes we only want to get new chart, so I do think it necessary.

**Comment by Neskol** [comment]
Yes this is certainly the stuff I am working on. I did not plan to do this differential update package is because for iOS at least, assuming you are using MaipadDX then iOS will not substitude exisiting files for you - I can already see there are tons of questions when importing new charts. Thus, I always suggest to do a clean reinstall to avoid such problem... or if you are using Android then you know what to do.
